version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongoDB_IoT
    ports:
      - "27017:27017"
    networks:
      - my_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - my_network
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  my_network:
    driver: bridge
